server:
  port: 8181

spring:
  application:
    name: dm
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:tenantdb}?useSSL=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

    jpa:
      database: postgresql
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          hbm2ddl:
            auto: none
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true


logging:
  pattern:
    correlation: "%clr(tenantId=%X{tenantId:-}){faint} "
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always

multitenancy:
  http:
    header-name: X-TenantId
  data:
    default-schema: default

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST_URL:localhost}:${KEYCLOAK_PORT:9999}/

keycloak-admin-cli: admin-cli
keycloak-realm-creator-username: realm-creator
keycloak-realm-creator-password: verysp2


